modLoader = "javafml"
loaderVersion = "[2,)" # NeoForge/FML loader version range
license = "All-Rights-Reserved"

[[mods]]
modId = "cobblemonupdater"
version = "${version}"
displayName = "CobblemonUpdater"
description = "updates cobblemon to the latest version"
authors = ""
displayURL = ""
logoFile = "assets/cobblemonupdater/icon.png"

[[dependencies.cobblemonupdater]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "SERVER"
